name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Debug Releases
        run: gh release list

      - name: Create Release
        run: gh release create ${{ github.ref_name }} -t "Release ${{ github.ref_name }}"
        
      - name: Clear pack.mcmeta
        run: echo -n > filename

      - name: Create pack.mcmeta
        run: |
          echo '{
            "pack": {
              "pack_format": 13,
              "description": "§7Author §f» §6WilderPizza\n§7Version §f» §7${{ github.ref_name }}"
            }
          }' > pack.mcmeta

      - name: Zip Project
        run: |
          find . -type f -not -path './.git/*' -not -path './.github/*' -exec zip -r pack.zip {} +

      - name: Upload Zip
        run: gh release upload ${{ github.ref_name }} pack.zip

      - name: Delete Zip
        run: rm pack.zip
